#easy_admin_bundle:
#    resource: '@EasyAdminBundle/Controller/AdminController.php'
#    prefix: /admin
#    type: annotation

easy_admin_bundle:
    # this is just an example; update the value of 'resource' accordingly
    resource: 'App\Controller\AdminController'
    type:     annotation
    prefix:   /admin